config/routes.rb
Rails.application.routes.draw do
  root 'index#home'

  resources :students
  resources :courses
  resources :registrations, only: [:new, :create, :destroy]

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/course.rb
class Course < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 45 }
  validates :description, presence: true, length: { maximum: 45 }
  has_many :students, class_name:  "Registration",
  					  foreign_key: "course_id",
   					  dependent:   :destroy
end

app/models/registration.rb
class Registration < ActiveRecord::Base
  belongs_to :course,  class_name: "Course"
  belongs_to :student, class_name: "Student"
  validates :student_id, presence: true
  validates :course_id,  presence: true
  validates_uniqueness_of :course_id, scope: :student_id
end

app/models/student.rb
class Student < ActiveRecord::Base
  validates :name, presence: true, length: { maximum: 45 }
  validates :register_number, presence: true, length: { maximum: 45 }
  validates_uniqueness_of :register_number
  has_many :courses, class_name:  "Registration",
   					 foreign_key: "student_id",
   					 dependent:   :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  def index
    @courses = Course.all
  end

  def show
  end
  
  def new
    @course = Course.new
  end

  def edit
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, notice: 'Curso cadastrado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @course.update(course_params)
      redirect_to @course, notice: 'Curso atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @course.destroy
    redirect_to courses_url, notice: 'Curso excluído com sucesso.'
  end

  private
    def set_course
      @course = Course.find(params[:id])
    end

    def course_params
      params.require(:course).permit(:name, :description, :status)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def home
  end

  def new
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  
  before_action :get_select_box

  def new
  	@registration = Registration.new
  end

  def create
  	@registration = Registration.new(registration_params)
  	if @registration.save
  	  redirect_to new_registration_path, notice: 'Matrícula criada com sucesso.'
    else
      render :new
    end
  end

  def destroy
    @registration = Registration.find(params[:id])
    @registration.destroy
    redirect_to :back, notice: 'Matrícula removida com sucesso.'
  end

  private
    def registration_params
      params.require(:registration).permit(:student_id, :course_id)
    end

    def get_select_box
      @students = Student.all
      @courses  = Course.all
    end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController
  
  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
  	@student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    if @student.save
      redirect_to @student, notice: 'Estudante criado com sucesso.'
    else
      render :new
    end
  end

  def update
    if @student.update(student_params)
      redirect_to @student, notice: 'Estudante atualizado com sucesso.'
    else
      render :edit
    end
  end

  def destroy
    @student.destroy
    redirect_to students_url, notice: 'Estudante excluído com sucesso.'
  end

  private
    def set_student
      @student = Student.find(params[:id])
    end

    def student_params
      params.require(:student).permit(:name, :register_number, :status)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def nav_link(link_text, link_path, controller_name)
	if (controller.controller_name == controller_name)
	  class_name = 'active'
	else
	  class_name = ''
	end

	content_tag(:li, :class => class_name) do
	  link_to link_text, link_path
	end
  end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/courses/_form.html.erb
<%= form_for @course do |f| %>
	<% if @course.errors.any? %>
    <div class="alert alert-danger">
      <% @course.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    	<% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :name, class: "form-control", placeholder: "Nome do curso" %>
  </div>
  <div class="form-group">
    <%= f.label "descriçao" %>
    <%= f.text_area :description, class: "form-control" %>
  </div>

  <div class="checkbox">
    <label>
      <%= f.check_box :status, {}, 1, 0 %> Ativo
    </label>
  </div>
  <%= f.submit "Salvar", class: "btn btn-primary" %>
  <%= link_to "Voltar", courses_path, class: "btn btn-danger" %>
<% end %>

app/views/courses/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Editar curso</h2>
    <%= render "form" %>
  </div>
</div>

app/views/courses/index.html.erb
<h2>Cursos</h2>

<div class="well well-sm">
  <%= link_to "Cadastrar", new_course_path, class: "btn btn-default" %>
</div>

<%= render "layouts/message" %>

<% if @courses.count > 0 %>
  <table class="table table-bordered">
    <thead>
    	<tr>
    	  <th>Id</th>
    	  <th>Nome</th>
    	  <th></th>
    	</tr>
    </thead>
    <tbody>
    	<% @courses.each do |course| %>
    	  <tr>
    	    <td><%= course.id %></td>
    	    <td><%= course.name %></td>
    	    <td>
    	      <%= link_to "Detalhes", course_path(course) %>
    	      <%= link_to "Editar", edit_course_path(course) %>
    	      <%= link_to "Excluir", course, method: :delete, data: {confirm: "Tem certeza?"} %>
    	    </td>
    	  </tr>
    	<% end %>
    </tbody>
  </table>
<% else %>
  <p class="alert alert-warning">Nenhum curso cadastrado</p>
<% end %>

app/views/courses/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Cadastrar curso</h2>
    <%= render "form" %>
  </div>
</div>

app/views/courses/show.html.erb
<h2><%= @course.name %></h2>

<p><%= @course.description %></p>

<div class="row">
	<div class="col-md-8">
	  
	  <%= render "layouts/message" %>

	  <p><%= link_to "Editar", edit_course_path(@course) %></p>

	  <% if @course.students.count == 0 %>
	  	<p class="alert alert-warning">Nenhum aluno matriculado no curso</p>
	  <% else %>
	  	<h3>Alunos</h3>
	  	<table class="table">
	  	  <thead>
	  	  	<tr>
	  	  	  <th>Nome</th>
	  	  	  <th>Data da matrícula</th>
	  	  	  <th></th>
	  	  	 </tr>
	  	  </thead>
	  	  <tbody>
	  	  	<% @course.students.each do |registration| %>
	  	  	  <tr>
	  	  	  	<td><%= registration.student.name %></td>
	  	  	  	<td><%= registration.created_at %></td>
	  	  	  	<td>
	  	  	  		<%= link_to "Excluir", registration, method: :delete, data: {confirm: "Tem certeza?"} %>
	  	  	  	</td>
	  	  	  </tr>
	  	  	<% end %>
	  	  </tbody>
	  	</table>
	  <% end %>
	</div>
</div>
<%= link_to "Voltar", courses_path, class: "btn btn-danger" %>

app/views/index/home.html.erb
<h2>Bem-vindo</h2>

<p><%= link_to image_tag("rails.png", alt: "Rails logo"), 
				'http://rubyonrails.org/', target: "_blank" %></p>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    <a href="http://www.github.com/rodrigotavio91/projeto" target="_blank">Projeto</a> 
    desenvolvido por <a href="http://www.github.com/rodrigotavio91" target="_blank">Rodrigo Otavio</a>
  </small>
</footer>

app/views/layouts/_menu.html.erb
<ul class="sidebar-menu nav nav-pills nav-stacked">
  <%= nav_link "Home", root_path, 'index' %>
  <%= nav_link "Estudantes", students_path, 'students' %>
  <%= nav_link "Cursos", courses_path, 'courses' %>
  <%= nav_link "Matricular", new_registration_path, 'registrations' %>
</ul>

app/views/layouts/_message.html.erb
<% if !notice.blank? %>
  <div class="alert alert-success"><%= notice %></div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projeto</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
  	<div class="container">
  	  <div class="row">
  	  	<div class="col-md-3">
  	  	  <%= render "layouts/menu" %>
  	  	</div>
  	  	<div class="col-md-9">
  	  	  <%= yield %>
  	  	</div>
  	  </div>
      <%= render 'layouts/footer' %>
  	</div>
  </body>
</html>

app/views/students/_form.html.erb
<%= form_for @student do |f| %>
	<% if @student.errors.any? %>
    <div class="alert alert-danger">
      <% @student.errors.full_messages.each do |message| %>
        <p><%= message %></p>
    	<% end %>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :nome %>
    <%= f.text_field :name, class: "form-control", placeholder: "Nome do aluno" %>
  </div>
  <div class="form-group">
    <%= f.label "número da matrícula" %>
    <%= f.text_field :register_number, class: "form-control", 
                                       placeholder: "Número da matrícula do aluno" %>
  </div>
  <div class="checkbox">
    <label>
      <%= f.check_box :status, {}, 1, 0 %> Ativo
    </label>
  </div>
  
  <%= f.submit "Salvar", class: "btn btn-primary" %>
  <%= link_to "Voltar", students_path, class: "btn btn-danger" %>
<% end %>

app/views/students/edit.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Editar estudante</h2>
    <%= render "form" %>
  </div>
</div>

app/views/students/index.html.erb
<h2>Estudantes</h2>

<div class="well well-sm">
  <%= link_to "Cadastrar", new_student_path, class: "btn btn-default" %>
</div>

<%= render "layouts/message" %>

<% if @students.count > 0 %>
  <table class="table table-bordered">
    <thead>
    	<tr>
    	  <th>Id</th>
    	  <th>Nome</th>
    	  <th>Número de matrícula</th>
    	  <th></th>
    	</tr>
    </thead>
    <tbody>
    	<% @students.each do |student| %>
    	  <tr>
    	    <td><%= student.id %></td>
    	    <td><%= student.name %></td>
    	    <td><%= student.register_number %></td>
    	    <td>
    	      <%= link_to "Perfil", student_path(student) %>
    	      <%= link_to "Editar", edit_student_path(student) %>
    	      <%= link_to "Excluir", student, method: :delete, data: {confirm: "Tem certeza?"} %>
    	    </td>
    	  </tr>
    	<% end %>
    </tbody>
  </table>

<% else %>
  <p class="alert alert-warning">Nenhum estudante cadastrado</p>
<% end %>

app/views/students/new.html.erb
<div class="row">
  <div class="col-md-6">
    <h2>Cadastrar estudante</h2>
    <%= render "form" %>
  </div>
</div>

app/views/students/show.html.erb
<h2><%= @student.name %> <small><%= @student.register_number %></small></h2>

<div class="row">
  <div class="col-md-8">
    
    <%= render "layouts/message" %>

    <p><%= link_to "Editar", edit_student_path(@student) %></p>

    <% if @student.courses.count == 0 %>
  	  <p class="alert alert-warning">O aluno não esta matrículado em nenhum curso</p>
    <% else %>
  	  <h3>Cursos</h3>
  	  <table class="table">
  	    <thead>
  	  	  <tr>
  	  	    <th>Nome</th>
  	  	    <th>Data da matrícula</th>
  	  	    <th></th>
  	  	   </tr>
  	    </thead>
  	    <tbody>
  	      <% @student.courses.each do |registration| %>
  	        <tr>
  	          <td><%= registration.course.name %></td>
  	          <td><%= registration.created_at %></td>
  	          <td>
  	          	<%= link_to "Excluir", registration, method: :delete, data: {confirm: "Tem certeza?"} %>
  	          </td>
  	        </tr>
  	      <% end %>
  	    </tbody>
  	  </table>
    <% end %>
  </div>
</div>
<%= link_to "Voltar", students_path, class: "btn btn-danger" %>